#!/bin/bash
### BEGIN INIT INFO
# Provides:          choki-dar
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the chokidar server
### END INIT INFO

USER=root
SCRIPT_DIR='/home/pi/bin'
NAME=choki-dar
DAEMON=/home/pi/bin/chokidar
LOG='/var/log/choki-dar.log'
PIDFILE=/var/run/choki-dar.pid

. /lib/lsb/init-functions

start_daemon () {
        start-stop-daemon --start --chdir $SCRIPT_DIR --background \
        --chuid $USER --name $NAME \
                $START_STOP_OPTIONS --make-pidfile --pidfile $PIDFILE \
        --startas /bin/bash -- -c "exec $DAEMON >> $LOG 2>&1"
                log_end_msg 0
}

case "$1" in
        start)
            log_daemon_msg "Starting daemon" "$NAME"
            start_daemon
        ;;

        stop)
             log_daemon_msg "Stopping daemon" "$NAME"
                         start-stop-daemon --stop --quiet \
            --chuid $USER \
            --chdir $SCRIPT_DIR \
            --exec $DAEMON --pidfile $PIDFILE --retry 30 \
            --oknodo || log_end_msg $?
                        log_end_msg 0
        ;;

        restart)
			$0 stop
			sleep 5
			$0 start
		;;

		status)
        status_of_proc "$DAEMON" "$NAME"
        exit $?
        ;;

        *)
                echo "Usage: $0 {start|stop|restart}"
                exit 1
esac
exit 0
