#!/bin/bash
# /etc/init.d/chokidar.d

### BEGIN INIT INFO
# Provides:          chokidar
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: chokidar
# Description:       This service is used to manage a chokidar sensors
### END INIT INFO


case "$1" in 
    start)
        echo "Starting chokidar"
        /home/pi/bin/chokidar
        ;;
    stop)
        echo "Stopping chokidar"
        killall chokidar
        ;;
    *)
        echo "Usage: /etc/init.d/servod start|stop"
        exit 1
        ;;
esac

exit 0
